language: go
go:
  - 1.10.x
  - 1.11.x

install:
  go get golang.org/x/tools/cmd/cover
  go get github.com/mattn/goveralls
script:
  go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    secure: m7fWfAh3RPtFSZ7964qV4P6Y5BF4sNTwQE3QSTd0lsdWgS6h/7X3Cupm/FOb5TJgUi5Fgn1zPpNA0V2Kf6RHGzoz25OEvLyGiLy49hyizVusi8JVh7mCR+zPyGMjOfh1NAJok4o9hrn39vzYBFyHWRNBeC3D5BNV0jrPIkITm0Vfg8U4cOIw3molVhmAgVJXUMjaKt+Ca6tGeU6rJwIR3hvgN7hefJ7AXhoL1F35XUxI/E8yQwEI3yIOUeDbOf6I+/AENUaj8Z3y/QZJyhkbff2sRjSjjXQyv+xGiWl00DmY5ZnkykbL5nfDqYMmZG6T5KtiZJNwnrMvBA7md7yNYP1dYZg00yBDG3XR+IIoGhrvV5CfSbzBPgXLTgVLVl4PG8GghJXLGGrjLOzPeclcctabQRF3xCJjeN51xgeO7nfRtTwgj34KFIBExm30tMpdjlGJ9YcVrVFN0951Mo/bQS18kwNUPwntygJRHBTfIsbzUSU/8vzQdMroeaL07DXboNjIijnQaA33NVGv7bRcDpcun6cj02/Or+7zbg8UjAEK+kW8wPyxWRMRPTYGa4VDc9mee3IXCjrheRhW7ghQboM1Ch8cYL8o/+mPyBebav4YKp0BteejBFduwALhzAevzRuWbGb2oKe4m4ythOKUhGWbM94t89VpCGhV1Qhgmvc=
